//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATA.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int ID { get; set; }
        public int AccountID { get; set; }
        public string EntityName { get; set; }
        public int EntityID { get; set; }
        public string ActionType { get; set; }
        public System.DateTime ActionTime { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
