//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATA.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public string Description { get; set; }
        public string SourceType { get; set; }
        public string RequestedByFullName { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string IssueState { get; set; }
        public string Remarks { get; set; }
        public int CreatedByAccountID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int UpdatedByAccountID { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Store Store { get; set; }
    }
}
