//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATA.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectVersion
    {
        public int ActionID { get; set; }
        public int ProjectID { get; set; }
        public int CountryID { get; set; }
        public string ProjectName { get; set; }
        public string Remarks { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Country Country { get; set; }
    }
}
