//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATA.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Issue = new HashSet<Issue>();
            this.StoreAccount = new HashSet<StoreAccount>();
        }
    
        public int ID { get; set; }
        public string StoreName { get; set; }
        public int ProjectID { get; set; }
        public int CityID { get; set; }
        public string Address { get; set; }
        public int CreatedByAccountID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int UpdatedByAccountID { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue> Issue { get; set; }
        public virtual Project Project { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreAccount> StoreAccount { get; set; }
    }
}
