//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATA.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vIssue
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string IssueState { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestedByFullName { get; set; }
        public string SourceType { get; set; }
        public int StoreID { get; set; }
        public string StoreName { get; set; }
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public int CityID { get; set; }
        public string CityName { get; set; }
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public int CreatedByAccountID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int UpdatedByAccountID { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
