//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATA.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMail
    {
        public int ID { get; set; }
        public bool IsBodyHtml { get; set; }
        public string MailBody { get; set; }
        public string State { get; set; }
        public string Subject { get; set; }
        public int TryCount { get; set; }
        public System.DateTime LastTryTime { get; set; }
    }
}
