//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATA.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProject
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string Remarks { get; set; }
        public int CreatedByAccountID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int UpdatedByAccountID { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
