//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MATA.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStoreAccount
    {
        public int ID { get; set; }
        public int StoreID { get; set; }
        public string StoreName { get; set; }
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public int CityID { get; set; }
        public string CityName { get; set; }
        public int AccountID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    }
}
